# Generated by Django 5.2.3 on 2025-06-20 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_storedfile_user'),
        ('ml_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'ML запрос', 'verbose_name_plural': 'ML запросы'},
        ),
        migrations.AddField(
            model_name='mlrequest',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AddField(
            model_name='mlrequest',
            name='request_type',
            field=models.CharField(choices=[('ocr', 'OCR обработка'), ('ner', 'NER обработка'), ('predict', 'ML предсказание'), ('unknown', 'Неизвестный тип')], default='unknown', max_length=20, verbose_name='Тип запроса'),
        ),
        migrations.AddField(
            model_name='mlrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='mlrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='mlrequest',
            name='input_data',
            field=models.JSONField(verbose_name='Входные данные'),
        ),
        migrations.AlterField(
            model_name='mlrequest',
            name='result',
            field=models.JSONField(blank=True, null=True, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='mlrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='MLResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('ocr', 'Распознавание текста (OCR)'), ('ner', 'Извлечение сущностей (NER)')], max_length=3, verbose_name='Сервис')),
                ('result', models.JSONField(verbose_name='Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storedfile', verbose_name='Файл')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ml_api.mlrequest', verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'ML результат',
                'verbose_name_plural': 'ML результаты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file', 'service'], name='ml_api_mlre_file_id_787c9d_idx'), models.Index(fields=['created_at'], name='ml_api_mlre_created_0775ef_idx')],
            },
        ),
    ]
